### ISSUE TITLE
Permissions for Android 6.0

### ISSUE THREAD

**Issue by jmsalcido** [jmsalcido/catapi-android#46]
I cant save images if I dont give explicit permissions to Android to allow read/write permission

**Comment by jmsalcido** [comment]
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Pictures/voted_cats/birman_sv.jpg: open failed: EACCES (Permission denied)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:452)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at org.otfusion.caturday.util.FileUtils.prepareOutputStream(FileUtils.java:36)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at org.otfusion.caturday.service.images.picasso.StorageTarget.onBitmapLoaded(StorageTarget.java:31)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at com.squareup.picasso.RequestCreator.into(RequestCreator.java:518)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at org.otfusion.caturday.service.images.picasso.StorageImagePicassoServiceImpl.saveImageIntoStorage(StorageImagePicassoServiceImpl.java:29)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at org.otfusion.caturday.service.CatServiceImpl.saveCatToFavorites(CatServiceImpl.java:43)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at org.otfusion.caturday.ui.fragments.MainFragment.handleFavoriteCatEvent(MainFragment.java:180)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at com.squareup.otto.Bus.dispatch(Bus.java:386)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at com.squareup.otto.Bus.post(Bus.java:338)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at org.otfusion.caturday.events.FavoriteCatEvent.executeEvent(FavoriteCatEvent.java:21)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at org.otfusion.caturday.ui.fragments.MainFragment$2.onClick(MainFragment.java:103)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at android.view.View.performClick(View.java:5198)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at android.view.View$PerformClick.run(View.java:21147)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at android.os.Looper.loop(Looper.java:148)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at libcore.io.Posix.open(Native Method)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-08 21:28:58.776 2168-2168/org.otfusion.caturday W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:438)

**Comment by jmsalcido** [comment]
fixing over 7aa785d39fb23995fc2535e1ec216ac44f70b041 waiting for travis.
